# Generated by Django 4.1.2 on 2022-12-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tourrequests_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourrequests',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
