# Generated by Django 4.1.2 on 2022-12-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_tourrequests_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_first_name', models.CharField(max_length=10)),
                ('student_second_name', models.CharField(max_length=10)),
                ('student_class', models.CharField(max_length=5)),
                ('kin_first_name', models.CharField(max_length=10)),
                ('kin_surname', models.CharField(max_length=10)),
                ('phone_number', models.IntegerField()),
                ('any_med_condition', models.BooleanField(default=False)),
                ('residence', models.CharField(max_length=20)),
            ],
        ),
    ]
