# Generated by Django 4.1.2 on 2022-12-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_enquiries_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
