# Generated by Django 4.1.2 on 2022-12-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_applications_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentEmails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='applications',
            options={'verbose_name_plural': 'Applications'},
        ),
        migrations.AlterModelOptions(
            name='enquiries',
            options={'verbose_name_plural': 'Enquiries'},
        ),
        migrations.AlterModelOptions(
            name='tourrequests',
            options={'verbose_name_plural': 'Tour requests'},
        ),
    ]
